window.ENTRY_INSIGHTS = (function () {
  var items = [];
  var seq = 1;
  function add(type, themes, keywords, text) {
    var id = 'E' + String(seq).padStart(3, '0');
    seq += 1;
    items.push({ id: id, type: type, themes: themes, keywords: keywords, text: text });
  }

  // Any
  add('any', ['any'], ['empty'], 'A short note still leaves a clear trace.');
  add('any', ['any'], ['repeat', 'again'], 'A repeat is signal, not noise.');
  add('any', ['calm'], ['pause', 'slow'], 'Slower moments can reveal cleaner edges.');
  add('any', ['focus'], ['map', 'pattern'], 'One line can sharpen the map.');
  add('any', ['stressed'], ['pressure', 'urgent'], 'Pressure changed the texture of attention.');
  add('any', ['curious'], ['question', 'why'], 'A question opened more room than a conclusion.');
  add('any', ['tired'], ['tired', 'low'], 'Low energy still leaves useful data.');
  add('any', ['any'], ['context'], 'Context often explains what blame cannot.');
  add('any', ['any'], ['assumption'], 'An assumption appeared before certainty.');
  add('any', ['any'], ['small', 'tiny'], 'Small moments can carry a full pattern.');
  add('any', ['any'], ['phone', 'scroll'], 'Attention moved before intention did.');
  add('any', ['any'], ['note'], 'Naming it made the shape easier to hold.');
  add('any', ['calm'], ['breathe', 'breath'], 'A breath can change the frame.');
  add('any', ['focus'], ['check', 'verify'], 'The missing check left a visible gap.');
  add('any', ['stressed'], ['react', 'tone'], 'Tone arrived earlier than clarity.');
  add('any', ['curious'], ['explore', 'new'], 'New paths look uncertain before they look useful.');
  add('any', ['tired'], ['late', 'sleep'], 'Fatigue redrew the margin for error.');
  add('any', ['any'], ['empty', 'quiet'], 'Even quiet entries keep the mirror active.');
  add('any', ['any'], ['tradeoff'], 'The tradeoff became visible after the move.');
  add('any', ['any'], ['again'], 'Same corner, clearer view.');
  add('any', ['any'], ['pattern'], 'Pattern first. Story second.');
  add('any', ['focus'], ['choice', 'decide'], 'Choice became clearer once written.');
  add('any', ['calm'], ['gentle', 'steady'], 'Steady effort still changes direction.');
  add('any', ['stressed'], ['rush', 'hurry'], 'Rush solved one moment and taxed the next.');
  add('any', ['curious'], ['signal', 'trace'], 'A small trace can reveal structure.');
  add('any', ['tired'], ['drained', 'fog'], 'Foggy days still leave clean evidence.');
  add('any', ['any'], ['projection'], 'Part of the read may come from the mirror.');
  add('any', ['any'], ['empty', 'blank'], 'Blank does not mean meaningless.');
  add('any', ['any'], ['context', 'angle'], 'A different angle shifted the meaning.');
  add('any', ['any'], ['repeat', 'loop'], 'Loops are maps asking to be read.');

  // Avoidable
  add('avoidable', ['any'], ['rush', 'fast'], 'Speed hid a small corner.');
  add('avoidable', ['any'], ['late', 'delay'], 'Time slipped before the signal did.');
  add('avoidable', ['any'], ['forgot', 'forget'], 'A small thread of memory dropped.');
  add('avoidable', ['focus'], ['skip', 'miss'], 'One step passed quietly.');
  add('avoidable', ['any'], ['scroll', 'phone'], 'Attention drift left a fingerprint.');
  add('avoidable', ['tired'], ['sleep', 'tired'], 'Low energy softened precision.');
  add('avoidable', ['stressed'], ['stress', 'pressure'], 'Pressure narrowed the frame.');
  add('avoidable', ['any'], ['reaction', 'react'], 'Reaction arrived before reflection.');
  add('avoidable', ['any'], ['argue', 'fight'], 'Heat rose as clarity fell.');
  add('avoidable', ['focus'], ['tabs', 'multitask'], 'Too many threads, one missing stitch.');
  add('avoidable', ['any'], ['later', 'procrast'], 'Later came back as urgency.');
  add('avoidable', ['stressed'], ['panic', 'overwhelm'], 'Overwhelm chose the shortest path.');
  add('avoidable', ['any'], ['interrupt'], 'A line broke in the middle.');
  add('avoidable', ['calm'], ['assumption'], 'Assumption filled the open space.');
  add('avoidable', ['any'], ['detail'], 'A tiny detail ran the outcome.');
  add('avoidable', ['any'], ['careless', 'sloppy'], 'Care slipped for a moment.');
  add('avoidable', ['tired'], ['burnout', 'drained'], 'Friction can be fatigue in plain clothes.');
  add('avoidable', ['any'], ['hungry', 'food'], 'Body signals were quieter than the plan.');
  add('avoidable', ['any'], ['overcommit', 'too much'], 'Capacity was priced too optimistically.');
  add('avoidable', ['stressed'], ['deadline'], 'Deadline energy took the wheel.');
  add('avoidable', ['any'], ['avoid', 'avoidance'], 'Avoiding it made it heavier.');
  add('avoidable', ['focus'], ['noise', 'distract'], 'Noise won this round.');
  add('avoidable', ['any'], ['overthink'], 'Thinking became a loop.');
  add('avoidable', ['any'], ['impulse'], 'An impulse signed off quickly.');
  add('avoidable', ['any'], ['yes', 'promise'], 'A fast yes carried a hidden cost.');
  add('avoidable', ['calm'], ['comfort', 'habit'], 'Habit moved before awareness.');
  add('avoidable', ['any'], ['keys', 'anchor'], 'A small anchor was missing.');
  add('avoidable', ['focus'], ['bug', 'error'], 'A tiny error carried full weight.');
  add('avoidable', ['any'], ['repeat', 'again'], 'Same shape, different day.');
  add('avoidable', ['stressed'], ['anger', 'mad'], 'Anger colored the edges.');
  add('avoidable', ['any'], ['blame'], 'Blame arrived faster than learning.');
  add('avoidable', ['any'], ['compare'], 'Comparison took more than it gave.');
  add('avoidable', ['tired'], ['lazy'], 'It looked like laziness; energy may be the root.');
  add('avoidable', ['any'], ['doomscroll', 'scroll'], 'The feed asked for more than it returned.');
  add('avoidable', ['focus'], ['save'], 'The save step never landed.');
  add('avoidable', ['any'], ['rude', 'tone'], 'Sharp edges appeared in the exchange.');
  add('avoidable', ['any'], ['ignore'], 'Something important went unvisited.');
  add('avoidable', ['stressed'], ['control'], 'Control tightened the frame.');
  add('avoidable', ['any'], ['default', 'autopilot'], 'Autopilot ran longer than needed.');
  add('avoidable', ['any'], ['shortcut'], 'The shortcut delayed the real cost.');

  // Fertile
  add('fertile', ['any'], ['try', 'attempt'], 'An attempt happened. That counts.');
  add('fertile', ['curious'], ['new', 'experiment'], 'A new move entered the system.');
  add('fertile', ['focus'], ['practice'], 'Practice leaves quiet evidence.');
  add('fertile', ['any'], ['learn', 'lesson'], 'A lesson surfaced in the gap.');
  add('fertile', ['stressed'], ['risk'], 'Risk appeared under pressure.');
  add('fertile', ['any'], ['feedback'], 'Feedback is data, not identity.');
  add('fertile', ['calm'], ['slow', 'pause'], 'Slower carried more clarity.');
  add('fertile', ['any'], ['adjust', 'change'], 'A small adjustment changed direction.');
  add('fertile', ['curious'], ['question', 'why'], 'A better question arrived.');
  add('fertile', ['any'], ['draft'], 'A draft is proof of movement.');
  add('fertile', ['focus'], ['iterate', 'again'], 'Iteration gave the pattern texture.');
  add('fertile', ['any'], ['test'], 'A test ran. Information arrived.');
  add('fertile', ['tired'], ['tired'], 'Even tired, the experiment stayed alive.');
  add('fertile', ['any'], ['share'], 'Sharing the attempt lightened the load.');
  add('fertile', ['curious'], ['explore'], 'Exploration left a usable trace.');
  add('fertile', ['any'], ['improve'], 'Improvement often looks small and real.');
  add('fertile', ['calm'], ['breathe'], 'A breath shifted the angle.');
  add('fertile', ['any'], ['reframe'], 'The frame changed and so did the weight.');
  add('fertile', ['focus'], ['plan'], 'The plan met reality and produced data.');
  add('fertile', ['any'], ['miss'], 'A miss can still be fertile.');
  add('fertile', ['stressed'], ['overwhelm'], 'Under load, a new path still appeared.');
  add('fertile', ['any'], ['habit'], 'New habits ask for patient repeats.');
  add('fertile', ['curious'], ['curious'], 'Curiosity moved first.');
  add('fertile', ['any'], ['note'], 'Writing it down is part of the learning.');
  add('fertile', ['focus'], ['constraint'], 'Constraints shaped a better move.');
  add('fertile', ['any'], ['different'], 'Different became useful data.');
  add('fertile', ['any'], ['skill'], 'Skill grows in tiny layers.');
  add('fertile', ['calm'], ['soft'], 'Soft effort still builds range.');
  add('fertile', ['any'], ['honest'], 'Honesty reduced friction.');
  add('fertile', ['stressed'], ['recover'], 'Recovery can be part of the experiment.');
  add('fertile', ['any'], ['small'], 'Small shifts compound quietly.');
  add('fertile', ['tired'], ['rest'], 'Rest can be the next useful move.');
  add('fertile', ['any'], ['learn'], 'Learning showed up between attempts.');
  add('fertile', ['focus'], ['repeat'], 'The workable part asked to be repeated.');
  add('fertile', ['curious'], ['prototype'], 'A rough version clarified the path.');
  add('fertile', ['any'], ['edge', 'stretch'], 'Stretch usually feels awkward first.');
  add('fertile', ['calm'], ['steady'], 'Steady repeats changed the baseline.');
  add('fertile', ['any'], ['retry'], 'Retry converted doubt into signal.');
  add('fertile', ['focus'], ['scope', 'simple'], 'Simplicity made progress visible.');
  add('fertile', ['any'], ['start', 'begin'], 'Starting was most of the shift.');

  // Observed
  add('observed', ['any'], ['rude', 'tone'], 'It looked sharp. What did it protect?');
  add('observed', ['any'], ['interrupt'], 'The interruption carried a signal.');
  add('observed', ['any'], ['blame'], 'Blame appeared. Need may be underneath.');
  add('observed', ['any'], ['control'], 'Control showed up as tightness.');
  add('observed', ['any'], ['late'], 'Late can mean many things in context.');
  add('observed', ['any'], ['ignore'], 'Being ignored leaves a clear mark.');
  add('observed', ['any'], ['lazy'], 'Lazy is a label; context may tell more.');
  add('observed', ['any'], ['ego'], 'Ego can look like armor.');
  add('observed', ['any'], ['judge', 'judgment'], 'Judgment arrived quickly.');
  add('observed', ['any'], ['annoy', 'triggered'], 'Annoyance can point to a value.');
  add('observed', ['any'], ['different'], 'Different is not automatically wrong.');
  add('observed', ['any'], ['harm'], 'If harm is real, clarity matters.');
  add('observed', ['any'], ['failed'], 'A failure happened. Conditions matter too.');
  add('observed', ['any'], ['unsure'], 'Uncertainty is still valid data.');
  add('observed', ['any'], ['bias', 'triggered'], 'Trigger first. Story second.');
  add('observed', ['stressed'], ['stress', 'pressure'], 'Pressure can shrink the room.');
  add('observed', ['calm'], ['quiet'], 'From calm, the pattern looks cleaner.');
  add('observed', ['focus'], ['detail'], 'One detail stood out. Why this one?');
  add('observed', ['curious'], ['why', 'question'], 'Curiosity can replace blame.');
  add('observed', ['tired'], ['tired'], 'Fatigue can mimic attitude.');
  add('observed', ['any'], ['respect'], 'Respect was touched in this moment.');
  add('observed', ['any'], ['cold', 'distance'], 'Distance can be self-protection.');
  add('observed', ['any'], ['sarcasm'], 'Sarcasm can hide a direct need.');
  add('observed', ['any'], ['complain'], 'Complaint may be a request in disguise.');
  add('observed', ['any'], ['excuse'], 'An excuse may be fear speaking quietly.');
  add('observed', ['any'], ['defensive'], 'Defensive often means exposed.');
  add('observed', ['any'], ['talk'], 'Who needed the floor most?');
  add('observed', ['any'], ['compete'], 'Competition energy changed the room.');
  add('observed', ['any'], ['dismiss'], 'Dismissal leaves a quiet bruise.');
  add('observed', ['any'], ['style'], 'Style differences can feel personal.');
  add('observed', ['any'], ['boundary'], 'Boundaries need clarity more than heat.');
  add('observed', ['any'], ['system'], 'Sometimes the system fails first.');
  add('observed', ['any'], ['maybe'], 'Awareness is already a full step.');
  add('observed', ['any'], ['assumption'], 'Assumption may be filling missing context.');
  add('observed', ['any'], ['projection'], 'Projection can color interpretation.');
  add('observed', ['any'], ['context'], 'Context shifted the meaning here.');
  add('observed', ['any'], ['pressure'], 'Pressure changed what looked obvious.');
  add('observed', ['any'], ['triggered'], 'Something internal got activated.');
  add('observed', ['any'], ['harm', 'boundary'], 'Impact and boundary both deserve space.');
  add('observed', ['any'], ['failed', 'system'], 'Outcome and system may both be part of this.');

  // Ensure 130+ rows while keeping valid structure and tone.
  add('any', ['any'], ['mirror'], 'Not a verdict, just a clearer mirror line.');
  add('avoidable', ['any'], ['loop'], 'The loop asked to be named.');
  add('fertile', ['any'], ['pivot'], 'A pivot became visible in real time.');
  add('observed', ['any'], ['assumption', 'context'], 'Assumption softened once context arrived.');
  add('any', ['any'], ['empty'], 'A brief line can still carry depth.');
  add('avoidable', ['focus'], ['review'], 'The review step remained implicit.');
  add('fertile', ['curious'], ['probe'], 'A probe uncovered hidden structure.');
  add('observed', ['stressed'], ['pressure', 'tone'], 'Pressure and tone intertwined.');
  add('any', ['calm'], ['steady'], 'Steady noticing changed the quality of recall.');
  add('any', ['any'], ['pattern', 'again'], 'Same signal, clearer day.');

  return items;
})();
